//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lvl2Lecture5HomeWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Departments
    {
        public int ID_Departments { get; set; }
        public string Name_Department { get; set; }
    }
}
